services:
  resitech-pro:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
